sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build --tag easy-toggles-api --build-arg BUILD_CONTEXT=api/ --file api/Dockerfile api/
  - docker run --rm easy-toggles-api
  - docker ps -a

script:
  - npm run lint
  - npm run test:unit
  - npm run test:integration
