sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build --tag easy-toggles-api --build-arg BUILD_CONTEXT=api/ --file api/Dockerfile api/

script:
  - docker run --rm easy-toggles-api npm run lint
  - docker run --rm easy-toggles-api npm run test:unit
  - docker run --rm easy-toggles-api npm run test:integration
